import * as core from '@actions/core';
import * as glob from '@actions/glob';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { basename, join } from 'node:path';
import { fractalHash } from 'fractal-hash';

async function run(): Promise<void> {
  try {
    const filesPattern = core.getInput('files', { required: true });
    const algorithm    = core.getInput('algorithm') || 'sha256';
    const size         = parseInt(core.getInput('size') || '64', 10);
    const outputDir    = core.getInput('output-dir') || 'fractal-checksums';

    // Validate algorithm
    if (!['sha256', 'sha512'].includes(algorithm)) {
      throw new Error(`Unsupported algorithm "${algorithm}". Use sha256 or sha512.`);
    }

    // Glob files
    const globber = await glob.create(filesPattern);
    const files   = await globber.glob();

    if (files.length === 0) {
      core.warning(`No files matched pattern: ${filesPattern}`);
      core.setOutput('markdown', '');
      core.setOutput('checksums-file', '');
      return;
    }

    // Create output directory
    mkdirSync(outputDir, { recursive: true });

    const rows: string[] = [];
    const checksumLines: string[] = [];

    for (const file of files) {
      const content  = readFileSync(file);
      const hash     = createHash(algorithm).update(content).digest('hex');
      const name     = basename(file);
      const shortHash = `${hash.substring(0, 16)}…`;

      // Generate fractal PNG
      const dataUrl   = await fractalHash(hash, { format: 'png', size, background: 'dark' });
      const base64    = dataUrl.split(',')[1] ?? '';
      const imageName = `fractal-${name}.png`;
      const imagePath = join(outputDir, imageName);
      writeFileSync(imagePath, Buffer.from(base64, 'base64'));

      core.info(`  ${name}: ${shortHash} → ${imagePath}`);

      rows.push(`| \`${name}\` | \`${hash}\` | ![${name}](${imagePath}) |`);
      checksumLines.push(`${hash}  ${name}`);
    }

    // Write checksums.txt
    const checksumsPath = join(outputDir, 'checksums.txt');
    writeFileSync(checksumsPath, checksumLines.join('\n') + '\n');
    core.info(`Checksums written to ${checksumsPath}`);

    // Build markdown table
    const markdown = [
      '## Release Checksums',
      '',
      `> Generated by [fractal-hash](https://github.com/YOUR_USERNAME/fractal-hash) using ${algorithm.toUpperCase()}`,
      '',
      '| File | Checksum | Fractal |',
      '|------|----------|---------|',
      ...rows,
      '',
    ].join('\n');

    core.setOutput('markdown', markdown);
    core.setOutput('checksums-file', checksumsPath);

    core.info(`\nGenerated fractals for ${files.length} file(s).`);
  } catch (error) {
    core.setFailed(error instanceof Error ? error.message : String(error));
  }
}

run();
